# Matrix -- means, Run Workflow / Jobs on multiple machines,
# Run with multiple and diff NPM Node Version.
# Run with Multiple and diff OS machins.
# Many More matrix.

# To define merix,
# 1. Use strategy 
# 2. Use matrix under the strategy.
# 3. define your matrix like os, node versions etc.

# To refer your matrix from strategy, use
# $ {{ matrix.operating-system }}
# $ {{ matrix.node-version }}

name: Matrix Include Exclude Demo
on: push
jobs:
  build:
    continue-on-error: true
    strategy:
      matrix:
        node-version: [18, 14, 16]
        operating-system: [ubuntu-latest, windows-latest]
        include:
          - node-version: 18
            operating-system: ubuntu-latest
        exclude:
          - node-version: 14
            operating-system: windows-latest

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Install NPM dependencies
        run: npm ci
        working-directory: Run-Job-step-Conditioanlly

      # - name: Build Project
      #   run: npm run build
      #   working-directory: Run-Job-step-Conditioanlly