# Env -- Your password saved.
# Env can be exposed on git repo and in your code.
# Secrets can't exposed bcz, secretes will be stored in your github accounts > Settings > secrets.
# Once you made a secretes and stored your username and password, it will never show your secrets

# Just use, secrets.MONGODB_USERNAME instead of env.MONGODB_USERNAME.
# You dont have to define secrets in your code like for env have to do.


name: Use Secrets for MongoDB
on:
  push:
    branches:
      - master
jobs:
  test:
    env:
      MONGODB_CONNECTION_PROTOCOL: mongodb+srv 
      MONGODB_CLUSTER_ADDRESS: cluster0.zlj6s.mongodb.net
      MONGODB_USERNAME: ${{ secrets.MONGODB_USERNAME }}
      MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
      PORT: 8080
    
    runs-on: ubuntu-latest
    steps:

      - name: Get code
        uses: actions/checkout@v4
      
      - name: Cache all npm steps.
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: retrive-cache-key-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        run: npm ci
        working-directory: EnvVarsDBSecrets

      - name: Run Server
        run: npm start & npx wait-on http://127.0.0.1:${{ env.PORT }}
        working-directory: EnvVarsDBSecrets


      # - name: Lint code
      #   run: npm run lint
      #   working-directory: EnvVarsDBSecrets
      - name: Test code
        run: npm run test
        working-directory: EnvVarsDBSecrets

      - name: Output Info.
        run: echo "MONGODB_USERNAME- ${{ secrets.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output Info.
        run: | 
          echo "MONGODB_USERNAME- ${{ secrets.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME": $MONGODB_DB_NAME"